language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - nightly
#   - hhvm

# https://docs.travis-ci.com/user/reference/trusty#PHP-images
matrix:
  include:
    - php: 5.3.3
      dist: precise

before_script:
  - chmod 777 -R ./
  - php -m

script:
  - find ./ -type f -print0 | while read -d $'\0' file; do if [ "${file##*.}" = "php" ]; then echo "Check $file"; php -l $file; echo "";  echo ""; fi; done
  - php test.php